/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import controller.Logic;
import model.User;

import java.io.Serializable;
import java.util.Locale;
import javax.swing.ImageIcon;

/**
 *
 *
 */
public class LoginScreen extends javax.swing.JFrame implements Serializable {
 private static final long serialVersionUID = 1L;

    /**
     * Creates new form Log
     */
    public LoginScreen() {
    	setTitle("S.A Hospitals Systems");
        initComponents();
        Locale.setDefault(new Locale("en","US"));
        languageComboBox.setSelectedIndex(0);
        emptyFields(user, password, login);
        password.setText("Password");
        jPanel2.setLayout(null);
        jPanel2.add(jSeparator3);
        jPanel2.add(jSeparator2);
        jPanel2.add(user);
        jPanel2.add(jLabel2);
        jPanel2.add(login);
        jPanel2.add(languageComboBox);
        jPanel2.add(password);
        jPanel2.add(jPanel3);
        jPanel2.add(jSeparator4);
        user.requestFocus();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        desktopPaneLogin = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setIcon(new ImageIcon(LoginScreen.class.getResource("/view/icons/222.png")));
        jLabel1.setBounds(62, 28, 280, 260);
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator1.setBounds(26, 319, 339, 6);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(75, 340, 297, 29);
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(50, 83, 0, 0);
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator2.setBounds(50, 157, 249, 10);
        user = new javax.swing.JTextField();
        user.setBounds(50, 137, 249, 17);
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator3.setBounds(50, 230, 249, 10);
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator4.setBounds(124, 447, 118, 10);
        jPanel3 = new javax.swing.JPanel();
        jPanel3.setBounds(112, 430, 135, 17);
        forgotPassword = new javax.swing.JLabel();
        languageComboBox = new javax.swing.JComboBox<>();
        languageComboBox.setBounds(139, 350, 75, 28);
        languageComboBox.setVisible(false);
        login = new javax.swing.JButton();
        login.setBounds(109, 260, 138, 28);
        password = new javax.swing.JPasswordField();
        password.setBounds(50, 201, 249, 29);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
          /*  public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            } */
        });

        desktopPaneLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                desktopPaneLoginMousePressed(evt);
            }
        });

        jPanel1.setBackground(new Color(240, 248, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(390, 500));


        jSeparator1.setForeground(new Color(51, 153, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new Color(51, 153, 204));
        jLabel3.setText("S.A Hospitals Systems");

        jPanel2.setBackground(new Color(0, 102, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(340, 0));


        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        user.setBackground(new Color(0, 102, 204));
        user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        user.setForeground(new java.awt.Color(204, 204, 204));
        user.setText("Username");
        user.setToolTipText("Username");
        user.setBorder(null);
        user.setCaretColor(new java.awt.Color(255, 255, 255));
        user.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userMousePressed(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                userKeyTyped(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(jPanel2.getBackground());
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
              //  jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
               // jPanel3MouseExited(evt);
            }
        });

        forgotPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forgotPassword.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassword.setText("Forgot Password?");
        forgotPassword.setToolTipText("");
        forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotPasswordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(forgotPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(forgotPassword)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        languageComboBox.setBackground(jPanel2.getBackground());
        languageComboBox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        languageComboBox.setForeground(new java.awt.Color(255, 255, 255));
        languageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English"}));
        languageComboBox.setBorder(null);
        languageComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageComboBoxActionPerformed(evt);
            }
        });

        login.setBackground(new Color(51, 153, 204));
        login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setBorder(null);
        login.setEnabled(false);
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                emptyFields(user,password,login);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                emptyFields(user,password,login);
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                emptyFields(user,password,login);
            }
        };
        user.getDocument().addDocumentListener(docListener);
        password.getDocument().addDocumentListener(docListener);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });

        password.setBackground(new Color(0, 102, 204));
        password.setForeground(new java.awt.Color(204, 204, 204));
        password.setText("Password");
        password.setToolTipText("Password");
        password.setBorder(null);
        password.setCaretColor(new java.awt.Color(255, 255, 255));
        password.setEchoChar('\u0000');
        password.setMaximumSize(new java.awt.Dimension(400, 400));
        password.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordMousePressed(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        jSeparator4.setVisible(false);
        login.getAccessibleContext().setAccessibleParent(desktopPaneLogin);

        desktopPaneLogin.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPaneLogin.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLoginLayout = new javax.swing.GroupLayout(desktopPaneLogin);
        desktopPaneLogin.setLayout(desktopPaneLoginLayout);
        desktopPaneLoginLayout.setHorizontalGroup(
            desktopPaneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLoginLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        desktopPaneLoginLayout.setVerticalGroup(
            desktopPaneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLoginLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(desktopPaneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jPanel1.add(jLabel1);
        jPanel1.add(jLabel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPaneLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

  /*  private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        ForgotPassword(this, languageComboBox);
    }                                    
*/
    private void userActionPerformed(java.awt.event.ActionEvent evt) {                                     
          if (login.isEnabled())
        loginActionPerformed(evt);
    }                                    

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {                                      
                    
           Boolean bool;
           String pass=password.getText();
           Verification(user.getText(),pass,this,languageComboBox);
    }                                     

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {                                 
          int key=evt.getKeyCode();
          ActionEvent ae = new ActionEvent(evt.getSource(), evt.getID(), evt.paramString());
          if(key==KeyEvent.VK_ENTER && login.isEnabled())        
          loginActionPerformed(ae);
            login.getInputMap().put(KeyStroke.getKeyStroke("SPACE"), "none");
    }                                

    private void userFocusGained(java.awt.event.FocusEvent evt) {                                 
         cleanUserField();
    }                                

    private void userKeyTyped(java.awt.event.KeyEvent evt) {                              
       cleanUserField();
    }                             

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {                                     
       
       Font font= new Font("Tahoma", Font.BOLD, 12);
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
       forgotPassword.setFont(font.deriveFont(attributes));
    }                                    

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {                                    
       Font font= new Font("Dialog", Font.PLAIN, 12);
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE, -1);
       forgotPassword.setFont(font.deriveFont(attributes));
    }                                                                   

    private void userFocusLost(java.awt.event.FocusEvent evt) {                               
         if (user.getText().isEmpty())
        {
            if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language")){
              user.setForeground(new Color(204,204,204));
              user.setText("Username");
            }
        }
    }                              

    private void desktopPaneLoginMousePressed(java.awt.event.MouseEvent evt) {                                              
     if (user.isFocusOwner() && user.getText().isEmpty())
        {
            if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language")){
            user.setForeground(new Color(204,204,204));
            user.setText("Username");
            }
        }
        else if (password.isFocusOwner() && password.getPassword().length<1)
        {
            if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language")){
            password.setForeground(new Color(204,204,204));
            password.setEchoChar('\u0000');
            password.setText("Password");
            }
        }
    }                                             

    private void forgotPasswordMouseEntered(java.awt.event.MouseEvent evt) {                                            
  
       Font font= new Font("Tahoma", Font.BOLD, 12);
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
       forgotPassword.setFont(font.deriveFont(attributes));
    }                                           

    private void forgotPasswordMouseExited(java.awt.event.MouseEvent evt) {                                           
       Font font= new Font("Dialog", Font.PLAIN, 12);
       Map attributes = font.getAttributes();
       attributes.put(TextAttribute.UNDERLINE, -1);
       forgotPassword.setFont(font.deriveFont(attributes));
    }                                          

    private void forgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {                                            
        ForgotPassword(this,languageComboBox);
    }                                           

    private void languageComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        

        if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language"))
       {
           user.setText("Username");
           password.setText("Password");
           cleanUserField();
           cleanPasswordField();
           Locale l = new Locale("en", "US");

       }
       user.setForeground(new Color(204,204,204));
       password.setForeground(new Color(204,204,204));
       password.setEchoChar('\u0000');
       login.setEnabled(false);
       login.setBackground(new Color(240,248,255)); 
    }                                                

    private void userMousePressed(java.awt.event.MouseEvent evt) {                                  

    }                                 

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {                                   
         if (password.getPassword().length<1)
        {
            if (languageComboBox.getSelectedItem().equals("English") || languageComboBox.getSelectedItem().equals("Choose a language")){
            password.setForeground(new Color(204,204,204));
            password.setEchoChar('\u0000');
            password.setText("Password");
            }
        }
    }                                  

    private void passwordMousePressed(java.awt.event.MouseEvent evt) {                                      
      
    }                                     

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (login.isEnabled())
        loginActionPerformed(evt);
    }                                        

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {                                  
        cleanPasswordField();
    }                                 

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {                                     
         cleanPasswordField();
    }                                    

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {                                      
        cleanPasswordField();
    }                                     

    private void userMouseClicked(java.awt.event.MouseEvent evt) {                                  
         cleanUserField();
    }                                 
 
    private void emptyFields(JTextField user, JPasswordField password, JButton login){
             if (user.getText().length()<4 || user.getForeground().equals(new Color(204,204,204)) || password.getPassword().length<4 || password.getForeground().equals(new Color(204,204,204))){
                login.setEnabled(false);
                login.setBackground(new Color(2,51,99)); 
             }
             else{
                login.setEnabled(true);
                login.setBackground(new Color(240,248,255)); 
                login.setForeground(Color.DARK_GRAY);
             }
    }
    
    private void cleanUserField()
    {
        int r,g,b;
        r=user.getForeground().getRed();
        g=user.getForeground().getGreen();
        b=user.getForeground().getBlue();
        if (user.getText().equals("Username") && (r==204 && g==204 && b==204))
            user.setText("");
        user.setForeground(Color.WHITE);
    }
    private void cleanPasswordField()
    {
         int r,g,b;
       String pass="Password";
        char[] arr=pass.toCharArray();
        Font font= new Font("Tahoma", Font.PLAIN, 13);
        r=password.getForeground().getRed();
        g=password.getForeground().getGreen();
        b=password.getForeground().getBlue();
        if (Arrays.equals(password.getPassword(), arr) && (r==204 && g==204 && b==204))
            password.setText("");
        password.setForeground(Color.WHITE);
        password.setEchoChar('\u25cf');
       password.setFont(font);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    
    public boolean Verification(String username, String password, LoginScreen login,JComboBox<String> language)
    {

            boolean bool=Logic.getInstance().userExists(username, password);
            if (bool==false)
             {
                 JOptionPane.showMessageDialog(null, "Invalid Username/Password");
                  return false;
             }
            else
            {
               MainMenu um=new MainMenu(username, password);
               um.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
               um.setVisible( true );
                login.dispose();
                return true;
            }
    }
    
    public void ForgotPassword(LoginScreen login,JComboBox<String> language)
    {
       view.ForgotPassword fp=new view.ForgotPassword();
       fp.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
       Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       fp.setSize(screenSize.width,screenSize.height);
       fp.pack();
       fp.setVisible( true );
       fp.languageComboBox.setSelectedItem(language.getSelectedItem());
       login.dispose();
       
    } 

    // Variables declaration - do not modify                     
    private javax.swing.JDesktopPane desktopPaneLogin;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JComboBox<String> languageComboBox;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField user;
    // End of variables declaration                   
}
